package httpapi

import (
	"errors"
	"net/http"
	"time"

	"github.com/FranciscoPLoureiro/HighConcurrencyTicketOffice/internal/correlation"
	"github.com/FranciscoPLoureiro/HighConcurrencyTicketOffice/internal/domain"
)

// acceptedResponse is what a successful purchase returns.
//
// Not the ticket, because there is no ticket yet — the document is generated by
// a worker seconds later. What the caller gets is the decision, which is the
// part that was contended and is now settled: the seat is theirs, and here is
// where to watch it being finished.
type acceptedResponse struct {
	PurchaseID    string    `json:"purchase_id"`
	CampaignID    string    `json:"campaign_id"`
	UserID        string    `json:"user_id"`
	Status        string    `json:"status"`
	CorrelationID string    `json:"correlation_id"`
	StatusURL     string    `json:"status_url"`
	CreatedAt     time.Time `json:"created_at"`
}

// statusResponse is what the status endpoint returns.
type statusResponse struct {
	PurchaseID string    `json:"purchase_id"`
	CampaignID string    `json:"campaign_id"`
	UserID     string    `json:"user_id"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// statusPath is where a caller watches a purchase being finished. Built in one
// place so the URL handed out in the 202 cannot drift from the route that
// serves it.
func statusPath(purchaseID string) string {
	return "/api/v1/tickets/" + purchaseID + "/status"
}

func (s *Server) handlePurchase(w http.ResponseWriter, r *http.Request) {
	userID, ok := userIDFrom(r.Context())
	if !ok {
		// Only reachable if the route is wired without the middleware.
		// Failing loudly beats attributing the purchase to nobody.
		s.writeInternalError(w, "purchase handler reached without an identity", nil)
		return
	}

	purchase, err := s.purchaser.Purchase(r.Context(), s.campaignID, userID,
		r.Header.Get(idempotencyKeyHeader))

	switch {
	case errors.Is(err, domain.ErrSoldOut):
		// 409 rather than 404 or 410: the campaign exists and the request
		// was well formed, it just lost the race for a finite resource.
		writeError(w, http.StatusConflict, "stock_exhausted",
			"there are no tickets left for this campaign")

	case errors.Is(err, domain.ErrAlreadyPurchased):
		writeError(w, http.StatusConflict, "already_purchased",
			"this account already holds a ticket for this campaign")

	case errors.Is(err, domain.ErrIdempotencyKeyReplayed):
		// The key produced a purchase once and the record of the answer has
		// gone — expired, or lost with the Redis it lived in. The request is
		// legitimate and was already carried out, so this is not a refusal
		// of it so much as an admission that the receipt is missing.
		writeError(w, http.StatusConflict, "idempotency_key_replayed",
			"this "+idempotencyKeyHeader+" already produced a purchase, and the original response is no longer available")

	case errors.Is(err, domain.ErrCampaignNotFound):
		writeError(w, http.StatusNotFound, "campaign_not_found",
			"no such campaign")

	case err != nil:
		s.writeInternalError(w, "purchase failed", err)

	default:
		// 202 rather than 200. The sale is decided and durably recorded; the
		// document is not, and saying 200 would promise a ticket that does
		// not exist for another two seconds. The brief's point about
		// responsiveness is exactly this: the caller should not hold a
		// connection open while a PDF is drawn.
		w.Header().Set("Location", statusPath(purchase.ID))
		s.writeJSON(w, http.StatusAccepted, acceptedResponse{
			PurchaseID:    purchase.ID,
			CampaignID:    purchase.CampaignID,
			UserID:        purchase.UserID,
			Status:        string(purchase.Status),
			CorrelationID: correlation.From(r.Context()),
			StatusURL:     statusPath(purchase.ID),
			CreatedAt:     purchase.CreatedAt,
		})
	}
}

func (s *Server) handlePurchaseStatus(w http.ResponseWriter, r *http.Request) {
	userID, ok := userIDFrom(r.Context())
	if !ok {
		s.writeInternalError(w, "status handler reached without an identity", nil)
		return
	}

	purchase, err := s.purchaser.ReadPurchase(r.Context(), s.campaignID, r.PathValue("id"))

	switch {
	case errors.Is(err, domain.ErrPurchaseNotFound):
		writeError(w, http.StatusNotFound, "purchase_not_found", "no such purchase")

	case err != nil:
		s.writeInternalError(w, "could not read purchase status", err)

	case purchase.UserID != userID:
		// 404 rather than 403. Saying "this exists but is not yours" tells a
		// caller that a purchase id they guessed is real, which is a slow way
		// to enumerate other people's tickets. The purchase does not exist as
		// far as they are concerned.
		writeError(w, http.StatusNotFound, "purchase_not_found", "no such purchase")

	default:
		s.writeJSON(w, http.StatusOK, statusResponse{
			PurchaseID: purchase.ID,
			CampaignID: purchase.CampaignID,
			UserID:     purchase.UserID,
			Status:     string(purchase.Status),
			CreatedAt:  purchase.CreatedAt,
			UpdatedAt:  purchase.UpdatedAt,
		})
	}
}
